In [145]:
import numpy as np

data = np.load('data.npy')
target = np.load('target.npy')

In [146]:
print(data.shape)
print(target.shape)

(280, 64)
(280,)


In [147]:
from sklearn.model_selection import train_test_split

train_data, test_data, train_target, test_target = train_test_split(data,target,test_size=0.2) #split data

In [148]:
print(train_data.shape, train_target.shape)
print(test_data, test_target)

(224, 64) (224,)
[[255 255 255 ... 255 255 255]
 [255 255 253 ... 255 255 253]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [254 255 255 ... 255 255 253]] [3 2 0 3 2 2 3 1 1 3 3 2 3 2 2 1 3 2 1 2 2 3 3 1 2 1 2 1 0 0 2 1 0 3 3 1 1
 2 1 2 0 2 2 2 0 3 3 1 0 2 0 2 0 1 3 1]


In [149]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier() # load the KNN algorithm

In [150]:
model.fit(train_data, train_target)
print('traning')

traning


In [151]:
predicted_target = model.predict(test_data)# predict the test data

In [152]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(test_target,predicted_target)

print('test: ', test_target)
print('test: ', predicted_target)

print('Accuracy:', acc)

test:  [3 2 0 3 2 2 3 1 1 3 3 2 3 2 2 1 3 2 1 2 2 3 3 1 2 1 2 1 0 0 2 1 0 3 3 1 1
 2 1 2 0 2 2 2 0 3 3 1 0 2 0 2 0 1 3 1]
test:  [3 1 0 3 3 2 3 1 1 3 3 0 3 0 2 1 3 2 1 2 2 3 0 1 2 1 2 1 2 1 0 1 0 3 0 1 1
 2 1 2 0 2 0 0 0 3 2 1 2 2 0 1 0 1 3 1]
Accuracy: 0.75


In [153]:
import joblib

joblib.dump(model,'KNN-model-for-handwritten-sinhala-characters.sav')

['KNN-model-for-handwritten-sinhala-characters.sav']

In [154]:
import numpy as np

test_data = np.load('test_data.npy')

#print(test_data[1])

result = model.predict(test_data)

print(result)

[1 1 0]
